/**
 * Scrivano 2.0 cloud workspace UI (spec §36, MVP increment 12).
 *
 * Entirely additive: the local-first experience is untouched. This panel
 * appears when the user configures a backend; it renders ONLY what the API
 * returns (every AI claim arrives already cited and citation-validated by
 * the server). Meeting Chat answers are generated by the user's LOCAL LLM
 * (src/lib/llm.ts) over server-retrieved excerpts of one meeting.
 */

import { detectProvider, generate } from '../lib/llm';
import type { Meeting, Settings } from '../shared/types';
import {
  ApiClient,
  ApiError,
  buildMeetingChatPrompt,
  loadCloudConfig,
  msToClock,
  parseCitationMarkers,
  saveCloudConfig,
  segmentsToPayload,
  type ChatMessage,
  type CloudConfig,
  type CloudGroup,
  type CloudMeeting,
} from '../lib/api';

function esc(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

type Route =
  | { page: 'setup' }
  | { page: 'signin' }
  | { page: 'dashboard' }
  | { page: 'meeting'; meeting: CloudMeeting; tab: 'intelligence' | 'chat' }
  | { page: 'review'; group: CloudGroup }
  | { page: 'search' };

export interface CloudDeps {
  container: HTMLElement;
  getSettings: () => Settings;
  getLocalMeetings: () => Meeting[];
  onToast: (msg: string) => void;
  onClose: () => void;
}

export class CloudPanel {
  private config: CloudConfig | null = loadCloudConfig();
  private client: ApiClient | null = null;
  private route: Route = { page: 'setup' };
  private groups: CloudGroup[] = [];
  private meetings: CloudMeeting[] = [];
  private workspaceId: string | null = null;
  private chatLog: ChatMessage[] = [];
  private chatThread: string | null = null;
  private busy = false;

  private deps: CloudDeps;

  constructor(deps: CloudDeps) {
    this.deps = deps;
    if (this.config) {
      this.client = new ApiClient(this.config);
      this.route = this.client.signedIn ? { page: 'dashboard' } : { page: 'signin' };
    }
  }

  async open(): Promise<void> {
    if (this.route.page === 'dashboard') await this.loadDashboard();
    else this.render();
  }

  private async loadDashboard(): Promise<void> {
    if (!this.client) return;
    try {
      const workspaces = await this.client.listWorkspaces();
      if (workspaces.length === 0) {
        const ws = await this.client.createWorkspace('My workspace');
        this.workspaceId = ws.id;
      } else {
        this.workspaceId = workspaces[0].id;
      }
      this.groups = await this.client.listGroups();
      this.meetings = await this.client.listMeetings();
      this.route = { page: 'dashboard' };
    } catch (err) {
      if (err instanceof ApiError && err.status === 401) {
        this.route = { page: 'signin' };
      } else {
        this.deps.onToast(`Cloud error: ${err instanceof Error ? err.message : err}`);
      }
    }
    this.render();
  }

  private header(title: string): string {
    const nav =
      this.client?.signedIn && this.route.page !== 'signin' && this.route.page !== 'setup'
        ? `<button class="btn btn-ghost" data-act="dash">Dashboard</button>
           <button class="btn btn-ghost" data-act="csearch">Search</button>
           <button class="btn btn-ghost" data-act="signout">Sign out (${esc(this.client.email ?? '')})</button>`
        : '';
    return `<div class="cloud-header">
      <h2>${esc(title)}</h2>
      <div class="cloud-nav">${nav}<button class="btn btn-ghost" data-act="close">Local mode ✕</button></div>
    </div>`;
  }

  private render(): void {
    const c = this.deps.container;
    switch (this.route.page) {
      case 'setup':
        c.innerHTML = `${this.header('Connect Scrivano Cloud')}
          <p class="cloud-hint">Point Scrivano at your own backend. Transcription and AI stay local —
          the server stores transcripts, groups, and approved memory. Leave local mode any time.</p>
          <form class="cloud-form" data-form="setup">
            <label>API server URL<input name="apiUrl" placeholder="http://localhost:8000" required></label>
            <label>Supabase URL<input name="supabaseUrl" placeholder="https://xyz.supabase.co" required></label>
            <label>Supabase anon key<input name="supabaseAnonKey" required></label>
            <button class="btn btn-primary" type="submit">Save & continue</button>
          </form>`;
        break;
      case 'signin':
        c.innerHTML = `${this.header('Sign in')}
          <form class="cloud-form" data-form="signin">
            <label>Email<input name="email" type="email" required autocomplete="email"></label>
            <label>Password<input name="password" type="password" required minlength="8" autocomplete="current-password"></label>
            <div class="cloud-row">
              <button class="btn btn-primary" type="submit">Sign in</button>
              <button class="btn" type="button" data-act="signup">Create account</button>
              <button class="btn btn-ghost" type="button" data-act="reconfig">Server settings</button>
            </div>
          </form>`;
        break;
      case 'dashboard': {
        const groupCards = this.groups
          .map(
            (g) => `<div class="cloud-card">
              <strong>${esc(g.name)}</strong> <span class="pill">${esc(g.group_type)}${g.is_inbox ? ' · inbox' : ''}</span>
              <div class="cloud-row">
                <button class="btn btn-small" data-act="review" data-id="${g.id}">Memory review</button>
              </div>
            </div>`,
          )
          .join('');
        const meetingRows = this.meetings
          .map(
            (m) => `<tr>
              <td><button class="btn btn-link" data-act="open-meeting" data-id="${m.id}">${esc(m.title)}</button></td>
              <td>${esc(this.groups.find((g) => g.id === m.group)?.name ?? '')}</td>
              <td>${m.segment_count} segments</td>
              <td><span class="pill">${esc(m.status)}</span></td>
            </tr>`,
          )
          .join('');
        const localOptions = this.deps
          .getLocalMeetings()
          .map((m) => `<option value="${m.id}">${esc(m.title)}</option>`)
          .join('');
        const groupOptions = this.groups
          .map((g) => `<option value="${g.id}">${esc(g.name)}</option>`)
          .join('');
        c.innerHTML = `${this.header('Cloud workspace')}
          <section class="cloud-section">
            <h3>Groups</h3>
            <div class="cloud-cards">${groupCards || '<p class="cloud-hint">No groups yet.</p>'}</div>
            <form class="cloud-row" data-form="new-group">
              <input name="name" placeholder="New group name" required>
              <button class="btn" type="submit">Create group</button>
            </form>
          </section>
          <section class="cloud-section">
            <h3>Meetings</h3>
            <table class="cloud-table"><tbody>${meetingRows || ''}</tbody></table>
            ${meetingRows ? '' : '<p class="cloud-hint">No cloud meetings yet.</p>'}
            ${
              localOptions && groupOptions
                ? `<form class="cloud-row" data-form="sync">
                    <select name="local">${localOptions}</select>
                    <span>→</span>
                    <select name="group">${groupOptions}</select>
                    <button class="btn btn-primary" type="submit" ${this.busy ? 'disabled' : ''}>
                      ${this.busy ? 'Syncing…' : 'Sync local meeting'}
                    </button>
                  </form>`
                : ''
            }
          </section>`;
        break;
      }
      case 'meeting': {
        const m = this.route.meeting;
        const tab = this.route.tab;
        c.innerHTML = `${this.header(m.title)}
          <div class="tabs">
            <button class="tab ${tab === 'intelligence' ? 'active' : ''}" data-act="tab-intel">Intelligence</button>
            <button class="tab ${tab === 'chat' ? 'active' : ''}" data-act="tab-chat">Meeting Chat</button>
          </div>
          <div class="cloud-body" id="cloud-meeting-body"><p class="cloud-hint">Loading…</p></div>`;
        if (tab === 'intelligence') void this.renderIntelligence(m);
        else this.renderChat(m);
        break;
      }
      case 'review': {
        c.innerHTML = `${this.header(`Memory review — ${this.route.group.name}`)}
          <div class="cloud-body" id="cloud-review-body"><p class="cloud-hint">Loading…</p></div>`;
        void this.renderReview(this.route.group);
        break;
      }
      case 'search':
        c.innerHTML = `${this.header('Search')}
          <form class="cloud-row" data-form="search">
            <input name="q" placeholder="Search meetings, transcripts, memory, decisions, tasks…" required>
            <button class="btn btn-primary" type="submit">Search</button>
          </form>
          <div class="cloud-body" id="cloud-search-results"></div>`;
        break;
    }
    this.bind();
  }

  private async renderIntelligence(m: CloudMeeting): Promise<void> {
    const body = this.deps.container.querySelector('#cloud-meeting-body');
    if (!body || !this.client) return;
    const intel = await this.client.getIntelligence(m.id);
    const section = (title: string, rows: string[]) =>
      rows.length ? `<h4>${title}</h4><ul>${rows.join('')}</ul>` : '';
    body.innerHTML =
      [
        section('Summary', intel.summary_sections.map((s) => `<li><em>${esc(s.kind)}</em>: ${esc(s.body)}</li>`)),
        section('Decisions', intel.decisions.map((d) => `<li>${esc(d.statement)} <span class="pill">${esc(d.status)}</span></li>`)),
        section('Tasks', intel.tasks.map((t) => `<li>${esc(t.title)} — ${t.owner_name ? esc(t.owner_name) : '<em>unassigned</em>'}${t.due_date ? ` · due ${esc(t.due_date)}` : ''} <span class="pill">${esc(t.status)}</span></li>`)),
        section('Commitments', intel.commitments.map((x) => `<li>${esc(x.text)}</li>`)),
        section('Questions', intel.questions.map((x) => `<li>${esc(x.text)} <span class="pill">${esc(x.status)}</span></li>`)),
        section('Risks', intel.risks.map((x) => `<li>${esc(x.risk)}</li>`)),
      ].join('') ||
      '<p class="cloud-hint">No derived intelligence for this meeting yet. It appears here once the processing pipeline posts cited artifacts.</p>';
  }

  private renderChat(m: CloudMeeting): void {
    const body = this.deps.container.querySelector('#cloud-meeting-body');
    if (!body) return;
    const log = this.chatLog
      .map((msg) => {
        const cites = msg.citations
          .map((c) => `<span class="pill" title="${esc(c.quote)}">cited</span>`)
          .join(' ');
        return `<div class="chat-msg chat-${msg.role}">
          <p>${esc(msg.text)}</p>
          ${msg.role === 'assistant' ? (msg.not_found ? '<span class="pill pill-warn">not in transcript</span>' : cites) : ''}
        </div>`;
      })
      .join('');
    body.innerHTML = `
      <p class="cloud-hint">Answers come from your local AI over this meeting's transcript only — nothing else. Uncited answers are refused.</p>
      <div class="chat-log">${log}</div>
      <form class="cloud-row" data-form="chat" data-meeting="${m.id}">
        <input name="q" placeholder="Ask about this meeting…" required ${this.busy ? 'disabled' : ''}>
        <button class="btn btn-primary" type="submit" ${this.busy ? 'disabled' : ''}>${this.busy ? 'Thinking…' : 'Ask'}</button>
      </form>`;
    this.bind();
  }

  private async renderReview(group: CloudGroup): Promise<void> {
    const body = this.deps.container.querySelector('#cloud-review-body');
    if (!body || !this.client) return;
    const review = await this.client.memoryReview(group.id);
    const active = await this.client.groupMemory(group.id);
    const pending = review.pending
      .map(
        (s) => `<div class="cloud-card">
          <p>${esc(s.statement)} <span class="pill">${esc(s.category)}</span>
          ${s.conflict_candidates.length ? '<span class="pill pill-warn">possible conflict</span>' : ''}</p>
          <div class="cloud-row">
            <button class="btn btn-small" data-act="sug" data-id="${s.id}" data-action="approve">Approve</button>
            <button class="btn btn-small" data-act="sug" data-id="${s.id}" data-action="reject">Reject</button>
          </div>
        </div>`,
      )
      .join('');
    const conflicts = review.conflicts
      .map(
        (cf) => `<div class="cloud-card cloud-conflict">
          <p><strong>Existing:</strong> ${esc(cf.existing_memory.statement)}</p>
          <p><strong>New:</strong> ${esc(cf.suggestion.statement)}</p>
          <div class="cloud-row">
            <button class="btn btn-small" data-act="conf" data-id="${cf.id}" data-action="keep_existing">Keep existing</button>
            <button class="btn btn-small" data-act="conf" data-id="${cf.id}" data-action="replace_existing">Replace</button>
            <button class="btn btn-small" data-act="conf" data-id="${cf.id}" data-action="keep_both">Keep both</button>
          </div>
        </div>`,
      )
      .join('');
    const memories = active
      .map((m) => `<li>${esc(m.statement)} <span class="pill">${esc(m.category)}</span> <span class="pill">v${m.version}</span></li>`)
      .join('');
    body.innerHTML = `
      <h4>Pending suggestions</h4>${pending || '<p class="cloud-hint">Nothing waiting for review.</p>'}
      <h4>Conflicts</h4>${conflicts || '<p class="cloud-hint">No open conflicts.</p>'}
      <h4>Active memory</h4><ul>${memories || '<li class="cloud-hint">No approved memory yet.</li>'}</ul>`;
    this.bind();
  }

  private bind(): void {
    const c = this.deps.container;
    c.querySelectorAll<HTMLButtonElement>('[data-act]').forEach((btn) => {
      btn.onclick = () => void this.action(btn);
    });
    c.querySelectorAll<HTMLFormElement>('form[data-form]').forEach((form) => {
      form.onsubmit = (e) => {
        e.preventDefault();
        void this.submit(form);
      };
    });
  }

  private async action(btn: HTMLButtonElement): Promise<void> {
    const act = btn.dataset.act;
    try {
      if (act === 'close') this.deps.onClose();
      else if (act === 'dash') await this.loadDashboard();
      else if (act === 'csearch') { this.route = { page: 'search' }; this.render(); }
      else if (act === 'signout') { this.client?.signOut(); this.route = { page: 'signin' }; this.render(); }
      else if (act === 'reconfig') { this.route = { page: 'setup' }; this.render(); }
      else if (act === 'signup') await this.signUpFromForm();
      else if (act === 'open-meeting') {
        const meeting = this.meetings.find((m) => m.id === btn.dataset.id);
        if (meeting) {
          this.chatLog = [];
          this.chatThread = null;
          this.route = { page: 'meeting', meeting, tab: 'intelligence' };
          this.render();
        }
      } else if (act === 'tab-intel' && this.route.page === 'meeting') {
        this.route = { ...this.route, tab: 'intelligence' };
        this.render();
      } else if (act === 'tab-chat' && this.route.page === 'meeting') {
        this.route = { ...this.route, tab: 'chat' };
        this.render();
      } else if (act === 'review') {
        const group = this.groups.find((g) => g.id === btn.dataset.id);
        if (group) { this.route = { page: 'review', group }; this.render(); }
      } else if (act === 'sug' && this.route.page === 'review') {
        await this.client!.resolveSuggestion(btn.dataset.id!, btn.dataset.action!);
        this.deps.onToast(`Suggestion ${btn.dataset.action}d`);
        this.render();
      } else if (act === 'conf' && this.route.page === 'review') {
        await this.client!.resolveConflict(btn.dataset.id!, btn.dataset.action!);
        this.deps.onToast('Conflict resolved');
        this.render();
      }
    } catch (err) {
      this.deps.onToast(err instanceof Error ? err.message : String(err));
    }
  }

  private async signUpFromForm(): Promise<void> {
    const form = this.deps.container.querySelector<HTMLFormElement>('form[data-form="signin"]');
    if (!form || !this.client) return;
    const data = new FormData(form);
    const result = await this.client.signUp(String(data.get('email')), String(data.get('password')));
    if (result.needsConfirmation) {
      this.deps.onToast('Check your email to confirm the account, then sign in.');
    } else {
      await this.loadDashboard();
    }
  }

  private async submit(form: HTMLFormElement): Promise<void> {
    const kind = form.dataset.form;
    const data = new FormData(form);
    try {
      if (kind === 'setup') {
        this.config = {
          apiUrl: String(data.get('apiUrl')).replace(/\/$/, ''),
          supabaseUrl: String(data.get('supabaseUrl')).replace(/\/$/, ''),
          supabaseAnonKey: String(data.get('supabaseAnonKey')),
        };
        saveCloudConfig(this.config);
        this.client = new ApiClient(this.config);
        this.route = this.client.signedIn ? { page: 'dashboard' } : { page: 'signin' };
        if (this.route.page === 'dashboard') await this.loadDashboard();
        else this.render();
      } else if (kind === 'signin' && this.client) {
        await this.client.signIn(String(data.get('email')), String(data.get('password')));
        await this.loadDashboard();
      } else if (kind === 'new-group' && this.client && this.workspaceId) {
        await this.client.createGroup(this.workspaceId, String(data.get('name')));
        await this.loadDashboard();
      } else if (kind === 'sync' && this.client) {
        await this.syncMeeting(String(data.get('local')), String(data.get('group')));
      } else if (kind === 'search' && this.client) {
        const { results } = await this.client.search(String(data.get('q')));
        const target = this.deps.container.querySelector('#cloud-search-results');
        if (target) {
          target.innerHTML = results.length
            ? `<ul>${results
                .map(
                  (r) => `<li><span class="pill">${esc(r.type)}</span> ${esc(r.text)}</li>`,
                )
                .join('')}</ul>`
            : '<p class="cloud-hint">No results in your workspace.</p>';
        }
      } else if (kind === 'chat' && this.route.page === 'meeting') {
        await this.askMeetingChat(this.route.meeting, String(data.get('q')));
      }
    } catch (err) {
      this.deps.onToast(err instanceof Error ? err.message : String(err));
    }
  }

  private async syncMeeting(localId: string, groupId: string): Promise<void> {
    if (!this.client) return;
    const local = this.deps.getLocalMeetings().find((m) => m.id === localId);
    if (!local) return;
    this.busy = true;
    this.render();
    try {
      const meeting = await this.client.createMeeting(groupId, local.title);
      const payload = segmentsToPayload(local.segments);
      if (payload.length) await this.client.postSegments(meeting.id, payload);
      await this.client.finishMeeting(meeting.id);
      this.deps.onToast(`Synced "${local.title}" (${payload.length} segments)`);
      await this.loadDashboard();
    } finally {
      this.busy = false;
      this.render();
    }
  }

  private async askMeetingChat(meeting: CloudMeeting, question: string): Promise<void> {
    if (!this.client) return;
    this.busy = true;
    this.chatLog.push({ id: 'local', role: 'user', text: question, citations: [], not_found: false });
    this.renderChat(meeting);
    try {
      const ask = await this.client.chatAsk(meeting.id, question, this.chatThread ?? undefined);
      this.chatThread = ask.thread;
      const settings = this.deps.getSettings();
      const provider = await detectProvider(settings.llmUrl);
      if (!provider.reachable) {
        this.deps.onToast('No local AI provider reachable — start Ollama/LM Studio to use Meeting Chat.');
        return;
      }
      const model = settings.llmModel || provider.models[0] || '';
      const raw = await generate(provider, model, buildMeetingChatPrompt(question, ask.excerpts));
      const answerText = raw.trim();
      const notFound = answerText.includes('NOT_FOUND') || ask.excerpts.length === 0;
      const citations = notFound ? [] : parseCitationMarkers(answerText, ask.excerpts);
      // an uncited "answer" is not an answer — degrade honestly (spec §27)
      const finalNotFound = notFound || citations.length === 0;
      const message = await this.client.chatAnswer(
        meeting.id,
        ask.thread,
        finalNotFound ? "This meeting's transcript does not contain that information." : answerText,
        citations,
        finalNotFound,
      );
      this.chatLog.push(message);
    } finally {
      this.busy = false;
      this.renderChat(meeting);
    }
  }
}

export { msToClock };
