# Generated by Django 6.0.7 on 2026-07-18 01:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('verbal', 'Verbal'), ('written', 'Written'), ('announcement', 'Announcement'), ('not_required', 'Not Required')], max_length=32)),
                ('policy_applied', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('meeting_type', models.CharField(blank=True, max_length=64)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recording', 'Recording'), ('processing', 'Processing'), ('complete', 'Complete'), ('partially_complete', 'Partial'), ('failed', 'Failed')], default='draft', max_length=32)),
                ('language', models.CharField(default='en', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speaker_label', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('validated', 'Validated'), ('stored', 'Stored'), ('transcribed', 'Transcribed'), ('diarized', 'Diarized'), ('segmented', 'Segmented'), ('embedded', 'Embedded'), ('context_retrieved', 'Context Retrieved'), ('summarized', 'Summarized'), ('entities_extracted', 'Entities Extracted'), ('memory_suggested', 'Memory Suggested'), ('chat_indexed', 'Chat Indexed'), ('group_index_updated', 'Group Index Updated'), ('notified', 'Notified')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('mic', 'Mic'), ('system', 'System'), ('mixed', 'Mixed'), ('upload', 'Upload')], default='mic', max_length=16)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('speaker_label', models.CharField(blank=True, max_length=64)),
                ('speaker_confidence', models.FloatField(blank=True, null=True)),
                ('start_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField()),
                ('original_text', models.TextField()),
                ('corrected_text', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
