# Generated by Django 6.0.7 on 2026-07-18 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_groupdocument_documentchunk'),
        ('meetings', '0002_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citations', models.JSONField(default=list)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('owner_source', models.CharField(blank=True, choices=[('stated', 'Stated'), ('manual', 'Manual')], max_length=16)),
                ('owner_suggested', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_source', models.CharField(blank=True, choices=[('stated', 'Stated'), ('manual', 'Manual')], max_length=16)),
                ('priority', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('definition_of_done', models.TextField(blank=True)),
                ('why', models.TextField(blank=True)),
                ('risk_if_delayed', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='groups.group')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='meetings.meeting')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='groups.person')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citations', models.JSONField(default=list)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('text', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_source', models.CharField(blank=True, choices=[('stated', 'Stated'), ('manual', 'Manual')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('kept', 'Kept'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='groups.group')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='meetings.meeting')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='groups.person')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citations', models.JSONField(default=list)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('statement', models.TextField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('discussed', 'Discussed'), ('tentative', 'Tentative'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('reversed', 'Reversed')], default='discussed', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='groups.group')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='meetings.meeting')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citations', models.JSONField(default=list)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='groups.group')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='meetings.meeting')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citations', models.JSONField(default=list)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('unanswered', 'Unanswered'), ('deferred', 'Deferred'), ('needs_external', 'Needs External'), ('needs_client', 'Needs Client')], default='unanswered', max_length=16)),
                ('answer', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='groups.group')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='meetings.meeting')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citations', models.JSONField(default=list)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('risk', models.TextField()),
                ('impact', models.TextField(blank=True)),
                ('mitigation', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='groups.group')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='meetings.meeting')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='groups.person')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SummarySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citations', models.JSONField(default=list)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('overview', 'Overview'), ('executive', 'Executive'), ('objectives', 'Objectives'), ('follow_up', 'Follow Up'), ('context_connections', 'Context Connections')], max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('body', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='groups.group')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='meetings.meeting')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.workspace')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
